services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    # ports:
    #   - ${SPEEDTEST_PORT_80:-8080}:80
    #   - ${SPEEDTEST_PORT_443:-8443}:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - APP_KEY=${SPEEDTEST_APP_KEY:?error} # How to generate an app key: https://speedtest-tracker.dev/
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=${SPEEDTEST_SCHEDULE:?error}
      - SPEEDTEST_SERVERS=${SPEEDTEST_SERVERS}
      - DISPLAY_TIMEZONE=${TZ}
    volumes:
      - ${SPEEDTEST_VOLUME:?error}:/config
      # - /path/to-custom-ssl-keys:/config/keys
    restart: always
    network_mode: container:gluetun
