services:
  ixaocan:
    container_name: ixaocan
    image: busybox:latest
    ports:
      - ${IXAOCAN_PORT_8080:-8080}:8080
    command: httpd -f -p 8080 -h /var/www/html
    volumes:
      - ./ixaocan:/var/www/html
    networks:
      - ixtal_shared

  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard:latest
    ports:
      - ${WIREGUARD_PORT_51820:-51820}:51820/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${WIREGUARD_TZ} # Replace with your timezone, e.g., Europe/London
      - SERVERURL=auto # Can be set to your server's URL if auto-detection fails
      - SERVERPORT=51820 # Default WireGuard port, change if your server uses a different port
      - PEERS=1 # Number of peer configurations to generate, if needed
      - PEERDNS=auto # Use auto or specify custom DNS servers
      - INTERNAL_SUBNET=10.12.12.0/24 # Adjust this if it conflicts with your network
    volumes:
      - ${WIREGUARD_VOLUME:?error}:/config # Replace with the path to your WireGuard config
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - ixtal_vpn
    restart: unless-stopped

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    ports:
      - ${ADGUARD_PORT_53:-53}:53/tcp
      - ${ADGUARD_PORT_53:-53}:53/udp
      # Uncomment other ports as needed
      # - ${ADGUARD_PORT_3000:-3000}:3000/tcp # Web interface
      # - ${ADGUARD_PORT_3000:-3000}:3000/udp # Alternate Web interface
      # - ${ADGUARD_PORT_80:-80}:80/tcp
      # - ${ADGUARD_PORT_443:-443}:443/tcp
      # - ${ADGUARD_PORT_443:-443}:443/udp # DNS-over-HTTPS
      # - '67:67/udp' # DHCP server
      # - '68:68/tcp' # DHCP server
      # - '68:68/udp' # DHCP server
      # - '853:853/tcp' # DNS-over-TLS
      # - '853:853/udp' # DNS-over-QUIC
      # - '5443:5443/tcp' # Alternate DNS-over-HTTPS port
      # - '5443:5443/udp' # Alternate DNS-over-HTTPS port
      # - '6060:6060/tcp' # Alternate Web interface port
    volumes:
      - ${ADGUARD_VOLUME:?error}/conf:/opt/adguardhome/conf
      - ${ADGUARD_VOLUME:?error}/work:/opt/adguardhome/work
    restart: unless-stopped
    networks:
      - ixtal_vpn
    depends_on:
      - wireguard

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:?error}
    restart: unless-stopped
    networks:
      - ixtal_vpn
    depends_on:
      - wireguard

networks:
  ixtal_shared:
    name: ixtal_shared
    driver: bridge
    ipam:
      config:
        - subnet: 169.0.0.0/16
          gateway: 169.0.0.1
  ixtal_vpn:
    name: ixtal_vpn
    driver: bridge
    ipam:
      config:
        - subnet: 142.0.0.0/16
          gateway: 142.0.0.1
