services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      - OPENVPN_USER=${OPENVPN_USER:?error}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD:?error}
      - DOT=off
      - DNS_ADDRESS=9.9.9.9 # Use public DNS servers initially
      - DNS_ADDRESS_FALLBACK=1.1.1.1 # Fallback DNS servers
      # - DNS_KEEP_NAMESERVER=on
      - HTTP_CONTROL_SERVER_ADDRESS=:8080
    ports:
      - ${ADGUARD_PORT_53:-53}:53/tcp
      - ${ADGUARD_PORT_53:-53}:53/udp
      # - ${ADGUARD_PORT_3000:-3000}:3000/tcp # Expose AdGuard Home web interface at first run
    volumes:
      - ./volumes/gluetun:/gluetun
    restart: always
    healthcheck:
      test: [ 'CMD', '/gluetun-entrypoint', 'healthcheck' ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    # ports:
    # - ${ADGUARD_PORT_53:-53}:53/tcp
    # - ${ADGUARD_PORT_53:-53}:53/udp
    # Uncomment other ports as needed
    # - ${ADGUARD_PORT_3000:-3000}:3000/tcp # Web interface
    # - ${ADGUARD_PORT_3000:-3000}:3000/udp # Alternate Web interface
    # - ${ADGUARD_PORT_80:-80}:80/tcp # Using 8181 to avoid gluetun conflicts
    # - ${ADGUARD_PORT_443:-443}:443/tcp
    # - ${ADGUARD_PORT_443:-443}:443/udp # DNS-over-HTTPS
    # - 67:67/udp # DHCP server
    # - 68:68/tcp # DHCP server
    # - 68:68/udp # DHCP server
    # - 853:853/tcp # DNS-over-TLS
    # - 853:853/udp # DNS-over-QUIC
    # - 5443:5443/tcp # Alternate DNS-over-HTTPS port
    # - 5443:5443/udp # Alternate DNS-over-HTTPS port
    # - 6060:6060/tcp # Alternate Web interface port
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ADGUARD_VOLUME:?error}/conf:/opt/adguardhome/conf
      - ${ADGUARD_VOLUME:?error}/work:/opt/adguardhome/work
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3000' ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    # ports:
    #   - ${PORTAINER_PORT_8000:-8000}:8000
    #   - ${PORTAINER_PORT_9443:-9443}:9443
    command: --http-disabled # Disable port 9000 to avoid conflicts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_VOLUME:?error}/data:/data
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:?error}
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
      adguardhome:
        condition: service_started

networks:
  vpn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
