services:
  ixaocan:
    container_name: ixaocan
    image: busybox:latest
    env_file:
      - stack.env
    ports:
      - ${PORT_8080:-8080}:8080
    command: httpd -f -p 8080 -h /var/www/html
    volumes:
      - ./public:/var/www/html

networks:
  default:
    name: ixtal_shared
    driver: bridge
    ipam:
      config:
        - subnet: 152.0.0.0/16
          gateway: 152.0.0.1
