services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - DOT=off
      - DNS_ADDRESS=9.9.9.9
    ports:
      - ${ADGUARD_PORT_53:-53}:53/tcp
      - ${ADGUARD_PORT_53:-53}:53/udp
      - ${ADGUARD_PORT_80:-80}:80/tcp
      - ${IXAOCAN_PORT_9090:-9090}:9090
    volumes:
      - ./gluetun:/gluetun
    restart: always

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    # ports:
    # - ${ADGUARD_PORT_53:-53}:53/tcp
    # - ${ADGUARD_PORT_53:-53}:53/udp
    # Uncomment other ports as needed
    # - ${ADGUARD_PORT_3000:-3000}:3000/tcp # Web interface
    # - ${ADGUARD_PORT_3000:-3000}:3000/udp # Alternate Web interface
    # - ${ADGUARD_PORT_80:-80}:80/tcp
    # - ${ADGUARD_PORT_443:-443}:443/tcp
    # - ${ADGUARD_PORT_443:-443}:443/udp # DNS-over-HTTPS
    # - 67:67/udp # DHCP server
    # - 68:68/tcp # DHCP server
    # - 68:68/udp # DHCP server
    # - 853:853/tcp # DNS-over-TLS
    # - 853:853/udp # DNS-over-QUIC
    # - 5443:5443/tcp # Alternate DNS-over-HTTPS port
    # - 5443:5443/udp # Alternate DNS-over-HTTPS port
    # - 6060:6060/tcp # Alternate Web interface port
    volumes:
      - ${ADGUARD_VOLUME:?error}/conf:/opt/adguardhome/conf
      - ${ADGUARD_VOLUME:?error}/work:/opt/adguardhome/work
    restart: unless-stopped
    network_mode: service:gluetun

  ixaocan:
    container_name: ixaocan
    image: busybox:latest
    command: httpd -f -p 9090 -h /var/www/html
    # ports:
    #   - ${IXAOCAN_PORT_9090:-9090}:9090
    volumes:
      - ./ixaocan:/var/www/html
    network_mode: service:gluetun

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:?error}
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - adguardhome
      - ixaocan
