services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=${TZ}
      # - VPN_TYPE=wireguard
      # - VPN_SERVICE_PROVIDER=protonvpn
      # - OPENVPN_USER=${OPENVPN_USER:?error}
      # - OPENVPN_PASSWORD=${OPENVPN_PASSWORD:?error}
      # - SERVER_COUNTRIES=${SERVER_COUNTRIES:?error}
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      - DOT=off
      - DNS_ADDRESS=9.9.9.9
      - HTTP_CONTROL_SERVER_ADDRESS=:8080
    ports:
      - ${ADGUARD_PORT_53:-53}:53/tcp
      - ${ADGUARD_PORT_53:-53}:53/udp
      - 9080:80/tcp # speedtest-tracker
    volumes:
      - ./volumes/gluetun:/gluetun
    restart: always

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    # ports:
    # - ${ADGUARD_PORT_53:-53}:53/tcp
    # - ${ADGUARD_PORT_53:-53}:53/udp
    # Uncomment other ports as needed
    # - ${ADGUARD_PORT_3000:-3000}:3000/tcp # Web interface
    # - ${ADGUARD_PORT_3000:-3000}:3000/udp # Alternate Web interface
    # - ${ADGUARD_PORT_80:-80}:80/tcp # Using 8181
    # - ${ADGUARD_PORT_443:-443}:443/tcp
    # - ${ADGUARD_PORT_443:-443}:443/udp # DNS-over-HTTPS
    # - 67:67/udp # DHCP server
    # - 68:68/tcp # DHCP server
    # - 68:68/udp # DHCP server
    # - 853:853/tcp # DNS-over-TLS
    # - 853:853/udp # DNS-over-QUIC
    # - 5443:5443/tcp # Alternate DNS-over-HTTPS port
    # - 5443:5443/udp # Alternate DNS-over-HTTPS port
    # - 6060:6060/tcp # Alternate Web interface port
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ADGUARD_VOLUME:?error}/conf:/opt/adguardhome/conf
      - ${ADGUARD_VOLUME:?error}/work:/opt/adguardhome/work
    restart: unless-stopped
    network_mode: service:gluetun

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:?error}
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - adguardhome
