services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    restart: unless-stopped
    dns:
      - ${IXTAL_DNS_IP:-9.9.9.9}
      - 1.1.1.1

networks:
  default:
    external: true
    name: ixtal_shared
