version: '3.9'

services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:v0.107.48
    ports:
      - 53:53/tcp
      - ${PORT_80}:80/tcp
      - 443:443/tcp
      - ${PORT_3000}:3000/tcp
      - 853:853/tcp
      - 5443:5443/tcp
      - 6060:6060/tcp
      - 53:53/udp
      - 67:67/udp
      - ${PORT_68}:68/udp
      - 443:443/udp
      - 853:853/udp
      - 5443:5443/udp
    volumes:
      - ${ADGUARD_VOLUME}/conf:/opt/adguardhome/conf
      - ${ADGUARD_VOLUME}/work:/opt/adguardhome/work
    restart: unless-stopped
    # networks:
    #   - adguardhome_network
    #   - ixtal_shared
    networks:
      ixtal_shared:
        ipv4_address: ${ADGUARD_DNS_IP}

networks:
  # adguardhome_network:
  #   name: adguardhome_network
  #   driver: bridge
  ixtal_shared:
    external: true
