version: '3.9'

services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    restart: unless-stopped
    dns:
      - ${ADGUARD_DNS_IP}
      - 9.9.9.9
      - 1.1.1.1
    networks:
      # - cloudflared_network
      - ixtal_shared

networks:
  # cloudflared_network:
  #   name: cloudflared_network
  #   driver: bridge
  ixtal_shared:
    external: true
