version: '3.9'

services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - cloudflared_network

networks:
  cloudflared_network:
    name: cloudflared_network
    driver: bridge
