version: '3.9'

services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${NEXTCLOUD_VOLUME}/config:/config
      - ${NEXTCLOUD_VOLUME}/data:/data
    ports:
      - ${PORT}:443
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    restart: unless-stopped
    dns:
      - ${ADGUARD_DNS_IP}
      - 9.9.9.9
      - 1.1.1.1
    networks:
      # - nextcloud_network
      - ixtal_shared

  nextcloud_db:
    image: linuxserver/mariadb:latest
    container_name: nextcloud_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${NEXTCLOUD_VOLUME}/db:/config
    restart: unless-stopped
    dns:
      - ${ADGUARD_DNS_IP}
      - 9.9.9.9
      - 1.1.1.1
    networks:
      # - nextcloud_network
      - ixtal_shared

  nextcloud_redis:
    image: redis:7.2.4-alpine3.19
    container_name: nextcloud_redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - ${NEXTCLOUD_VOLUME}/redis:/data
    restart: unless-stopped
    dns:
      - ${ADGUARD_DNS_IP}
      - 9.9.9.9
      - 1.1.1.1
    networks:
      # - nextcloud_network
      - ixtal_shared

networks:
  # nextcloud_network:
  #   name: nextcloud_network
  #   driver: bridge
  ixtal_shared:
    external: true
