version: '3.9'

services:
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    ports:
      - ${PORT_9091}:9091
      - ${PORT_51413}:51413
      - ${PORT_51413}:51413/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - ${TRANSMISSION_VOLUME}/config:/config
      - ${TRANSMISSION_VOLUME}/downloads:/downloads
      - ${TRANSMISSION_VOLUME}/watch:/watch
    restart: always
    dns:
      - ${ADGUARD_DNS_IP}
      - 9.9.9.9
      - 1.1.1.1
    networks:
      # - transmission_network
      - ixtal_shared

networks:
  # transmission_network:
  #   name: transmission_network
  #   driver: bridge
  ixtal_shared:
    external: true
